-- ============================================================================
-- CAMINHOES
--
-- Cria a tabela de caminhoes da frota, com status, para o vendedor ver no
-- dashboard do app quais estao livres/em carga/em rota.
--
-- ID_CAMINHAO segue o mesmo padrao de auto-geracao que PEDIDOS.ID_PEDIDO ja
-- usa (GENERATED BY DEFAULT AS IDENTITY) -- o INSERT nao informa o id
-- manualmente, ele eh obtido via RETURNING id_caminhao INTO, como em
-- 01_criar_pedido_completo.sql.
--
-- Contrato de dados combinado com o time de frontend Flutter (nao pode
-- divergir, eles estao implementando em paralelo contra este mesmo schema).
--
-- Rode este script em: SQL Workshop > SQL Commands, no workspace
-- erp_rafaellourenco.
-- ============================================================================

CREATE TABLE caminhoes (
    id_caminhao   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa         VARCHAR2(10)  NOT NULL UNIQUE,
    modelo        VARCHAR2(100),
    status        VARCHAR2(20)  DEFAULT 'LIVRE' NOT NULL,
    motorista     VARCHAR2(100),
    data_cadastro DATE DEFAULT SYSDATE,
    CONSTRAINT chk_caminhoes_status CHECK (status IN ('LIVRE', 'EM_CARGA', 'EM_ROTA'))
);
